version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./build
    volumes:
      - '.:/var/www/app:consistent'
      - './build/php.ini:/etc/php/7.4/fpm/php.ini:ro'
      - './build/www.conf:/etc/php-fpm.d/:ro'
    depends_on:
      - db
    networks:
      - internal
  server:
    container_name: server
    image: nginx:1.17-alpine
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/app:consistent'
      - './build/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './build/server.conf:/etc/nginx/conf.d/default.conf:ro'
      - './var/log/nginx:/var/log/nginx:consistent'
    depends_on:
      - app
    networks:
      - internal
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: todo
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - './var/data:/var/lib/mysql:consistent'
    networks:
      - internal
networks:
  internal: